name: 'Build'

on:
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Set image tag and name'
        id: tag
        run: |
          IMAGE_TAG="0.0.0"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: 'Build deb'
        run: |
          VERSION=$IMAGE_TAG make

      - name: 'Upload Artifacts'
        if: ${{ !github.event.pull_request }}
        uses: actions/upload-artifact@v4
        with:
          name: sp-vm-watchdog-daemon_${{ steps.tag.outputs.image_tag }}-1_amd64.deb
          path: build/sp-vm-watchdog-daemon_${{ steps.tag.outputs.image_tag }}-1_amd64.deb
