name: 'Lint'

on:
  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Install lint tools'
        run: |
          python3 -m pip install -r app/lint_requirements.txt

      - name: 'Lint code'
        run: |
          make lint

